services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - bird-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  visitor-microapp:
    build:
      context: ./microapps/UI-Zoo
    ports:
      - "80:80"
    depends_on:
      - visitor-microservice

  visitor-microservice:
    build:
      context: ./microservices/bird-park-general
    ports:
      - "8080:8080"
    depends_on:
      - management-microservice

  management-microapp:
    build:
      context: ./microapps/Zoo-Management
    ports:
      - "81:80"
    depends_on:
      - management-microservice

  management-microservice:
    build:
      context: ./microservices/bird-park-management
    ports:
      - "8081:8081"
    depends_on:
      - database

volumes:
  bird-volume:
    driver: local